/**
 * Expo config plugin: background run-completion poller manifest entries.
 *
 * The app-level android/ directory is generated by `expo prebuild` (not
 * tracked), so the native poller's manifest declarations live here and are
 * injected on every prebuild:
 *   - FOREGROUND_SERVICE + FOREGROUND_SERVICE_DATA_SYNC + POST_NOTIFICATIONS
 *   - <service com.angussoftware.backgroundpoll.BackgroundPollService
 *        android:foregroundServiceType="dataSync" android:exported="false" />
 *
 * On Android 14+ a foreground service started with a type not declared on its
 * <service> element crashes (IllegalArgumentException), and starting one at
 * all requires the FOREGROUND_SERVICE permission — both easy to lose across
 * prebuild regenerations without this plugin.
 */
const { withAndroidManifest } = require("expo/config-plugins");

const SERVICE_CLASS = "com.angussoftware.backgroundpoll.BackgroundPollService";

function ensurePermission(manifest, name) {
  manifest["uses-permission"] = manifest["uses-permission"] || [];
  if (!manifest["uses-permission"].some((p) => p.$ && p.$["android:name"] === name)) {
    manifest["uses-permission"].push({ $: { "android:name": name } });
  }
}

function ensureService(manifest) {
  const appNode = manifest.application || [{}];
  const application = Array.isArray(appNode) ? appNode[0] : appNode;
  application.service = application.service || [];
  if (!application.service.some((s) => s.$ && s.$["android:name"] === SERVICE_CLASS)) {
    application.service.push({
      $: {
        "android:name": SERVICE_CLASS,
        "android:foregroundServiceType": "dataSync",
        "android:exported": "false",
      },
    });
  }
}

const withBackgroundPoll = (config) =>
  withAndroidManifest(config, (cfg) => {
    // modResults wraps the manifest in a document root ({ root: { manifest } }
    // in some SDK versions); unwrap to the actual <manifest> node.
    const manifest = cfg.modResults.manifest ?? cfg.modResults;
    ensurePermission(manifest, "android.permission.FOREGROUND_SERVICE");
    ensurePermission(manifest, "android.permission.FOREGROUND_SERVICE_DATA_SYNC");
    ensurePermission(manifest, "android.permission.POST_NOTIFICATIONS");
    ensureService(manifest);
    return cfg;
  });

module.exports = withBackgroundPoll;
